server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blast?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 20021225
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
